Films
Vakulaaa/movies pull request #2
Opened 2024-02-07 15:32 UTC by Vakulaaa

2024-02-07 18:46 UTC, y-u-n-ii-a commented on .gitignore
> +python
What is it?)

2024-02-07 18:48 UTC, y-u-n-ii-a commented on apps/authentication/migrations/0001_initial.py
> +# Generated by Django 4.2.8 on 2024-02-03 11:30
Just for the future: if migrations were already merged to the common branch never delete them

2024-02-07 18:48 UTC, y-u-n-ii-a commented on apps/authentication/migrations/0001_initial.py
> +# Generated by Django 4.2.8 on 2024-02-03 11:30
But for now, for our project it's ok

2024-02-07 18:49 UTC, y-u-n-ii-a commented on films/apps.py
> +    name = "films"
You should fix the name to "apps.films"

2024-02-07 18:50 UTC, y-u-n-ii-a commented on films/models.py
> +class Movie:
All models must inherit `models.Model`

2024-02-07 18:52 UTC, y-u-n-ii-a commented on films/models.py
> +    title = models.CharField("title", null=True)
Look, in the `User` model you have `Birthday` (in description). You should follow the same style and fix the description here:
```suggestion
    title = models.CharField("Title", null=True)
```

Moreover, the description by default will be the same, so you can just remove it

2024-02-07 18:53 UTC, y-u-n-ii-a commented on films/models.py
> +    title = models.CharField("title", null=True)
Make it not nullable

2024-02-07 18:54 UTC, y-u-n-ii-a commented on movies/settings.py
> +    "apps.authentication",
Don't forget to add new apps (`films`)

2024-02-07 18:56 UTC, y-u-n-ii-a commented on movies/settings.py
> +AUTH_MOVIE_MODEL = "authentication.Movie"
Remove it :)

2024-02-07 18:57 UTC, y-u-n-ii-a requested changes
Looks not bad, but some changes needed

2024-02-07 20:41 UTC, Vakulaaa commented on .gitignore
> +python
fixed

2024-02-07 20:42 UTC, Vakulaaa commented on apps/authentication/migrations/0001_initial.py
> +# Generated by Django 4.2.8 on 2024-02-03 11:30
ok, thanks

2024-02-07 20:42 UTC, Vakulaaa commented on films/apps.py
> +    name = "films"
fixed

2024-02-07 20:42 UTC, Vakulaaa commented on films/apps.py
> +    name = "films"
added

2024-02-07 20:43 UTC, Vakulaaa commented on films/models.py
> +class Movie:
fixed

2024-02-07 20:45 UTC, Vakulaaa commented on films/models.py
> +    title = models.CharField("title", null=True)
maked

2024-02-07 20:45 UTC, Vakulaaa commented on movies/settings.py
> +    "apps.authentication",
ok

2024-02-07 20:45 UTC, Vakulaaa commented on movies/settings.py
> +AUTH_MOVIE_MODEL = "authentication.Movie"
removed)

2024-02-12 12:15 UTC, y-u-n-ii-a approved these changes
Looks good to me!

2024-02-12 19:16 UTC, merged